"""``opsx-plan autopilot install`` — bind the autopilot unit to a repo and plan.

The shipped ``opsx-autopilot.service`` template is installed *disabled data*:
nothing renders it into the systemd user unit directory. This module owns that
binding step for operators and agents:

* resolve the repository (``--repo``/cwd) and the plan with the standard
  precedence (explicit ``--plan``, ``OPSX_PLAN``, active-plan pointer);
* read the installed unit and plan drop-in templates from the installed
  runtime tree (the repo checkout is the development fallback);
* render the unit verbatim and the drop-in with ``WorkingDirectory``,
  ``Environment=OPSX_PLAN``, a generated header, and an ``Environment=PATH=``
  line derived from the invoking environment (the directories providing
  ``openspec``, the adapter client, and node, then the systemd default
  directories);
* write both files under ``~/.config/systemd/user/`` idempotently, honoring
  ``--unit-name`` (validated as a single safe unit basename, so it can never
  escape the user unit directory or smuggle a ``systemctl`` option);
* run ``systemctl --user daemon-reload`` and ``enable`` (never ``start``).

``--print`` renders to stdout without touching the filesystem or invoking
``systemctl``.  All subprocess interaction goes through an injectable runner
and all path roots are injectable so tests never touch a real user manager.
systemd directive values (``WorkingDirectory``, ``Environment=``) are quoted
and escaped so literal repository, plan, and ``PATH`` values survive parsing.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

from lib.orchestrator import base, planref

DEFAULT_UNIT_NAME = "opsx-autopilot"

# Template locations relative to a runtime root (the installed tree or the
# development checkout), mirroring scripts/install-orchestrator.sh.
UNIT_TEMPLATE_REL = Path("systemd") / "opsx-autopilot.service.in"
DROPIN_TEMPLATE_REL = Path("systemd") / "opsx-autopilot.service.d" / "plan.conf.in"

SYSTEMD_USER_DIR_REL = Path(".config") / "systemd" / "user"

# The directories a systemd user unit inherits when its PATH is otherwise
# unset; appending them keeps the toolchain dirs additive rather than
# replacement.
SYSTEMD_DEFAULT_PATH = (
    "/usr/local/sbin",
    "/usr/local/bin",
    "/usr/sbin",
    "/usr/bin",
    "/sbin",
    "/bin",
)

# Toolchain executables whose directories must survive into the unit's PATH,
# in order around the per-plan adapter client (see adapter_client): openspec,
# the adapter client, node.
TOOLCHAIN_HEAD = "openspec"
TOOLCHAIN_TAIL = "node"

# Marks the managed files as generated so hand-edits are understood to be
# overwritten on the next install.
GENERATED_HEADER = (
    "# Generated by `opsx-plan autopilot install`; do not edit by hand.\n"
    "# Re-run the command to regenerate this file.\n"
)

# A safe systemd unit basename: starts with an alphanumeric (so it can never be
# mistaken for a `systemctl` option) and continues with the characters systemd
# permits in unit names.  Slashes, whitespace, traversal, and escapes are
# excluded by construction.
UNIT_NAME_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9:_.@-]*\Z")

UNIT_NAME_SUFFIX = ".service"


class InstallError(Exception):
    """A resolution, render, or systemctl failure for ``autopilot install``."""


def _default_user_unit_dir() -> Path:
    return Path.home() / SYSTEMD_USER_DIR_REL


def adapter_client(adapter: str) -> str:
    """Executable name for *adapter*, per the shared adapter table."""
    return base.ADAPTER_CLIENTS.get(adapter, adapter)


def template_roots(template_root: Path | None = None) -> list[Path]:
    """Candidate runtime roots that may carry the ``systemd/`` templates.

    Precedence is the entrypoint's own runtime search order (the installed
    runtime tree), then the root derived from this module's location (the
    development checkout when running from a clone).
    """
    if template_root is not None:
        return [Path(template_root)]

    roots: list[Path] = []
    seen: set[Path] = set()
    module_root = Path(__file__).resolve().parents[2]
    for root in list(base._RUNTIME_ROOTS) + [module_root]:
        root_path = Path(root)
        if root_path in seen:
            continue
        seen.add(root_path)
        roots.append(root_path)
    return roots


def resolve_template_root(template_root: Path | None = None) -> Path:
    """Return the runtime root whose ``systemd/`` carries both templates."""
    candidates = template_roots(template_root)
    for root in candidates:
        unit = root / UNIT_TEMPLATE_REL
        dropin = root / DROPIN_TEMPLATE_REL
        if unit.is_file() and dropin.is_file():
            return root
    looked = ", ".join(str(c) for c in candidates)
    raise InstallError(
        "could not locate the autopilot systemd templates "
        f"(looked in: {looked}); reinstall the orchestrator"
    )


def _toolchain_dirs(adapter: str, which_func) -> list[str]:
    dirs: list[str] = []
    names = (TOOLCHAIN_HEAD, adapter_client(adapter), TOOLCHAIN_TAIL)
    for name in names:
        found = which_func(name)
        if not found:
            continue
        directory = str(Path(found).resolve().parent)
        if directory in dirs:
            continue
        if Path(directory).is_dir():
            dirs.append(directory)
    return dirs


def derive_path(adapter: str, *, which_func=shutil.which) -> str:
    """Build the unit ``PATH`` value from the invoking environment.

    The directories providing ``openspec``, the adapter client, and node come
    first (in that order, de-duplicated), followed by the systemd default
    directories so the value is additive, not a replacement.
    """
    dirs = _toolchain_dirs(adapter, which_func)
    for directory in SYSTEMD_DEFAULT_PATH:
        if directory not in dirs:
            dirs.append(directory)
    return ":".join(dirs)


def _quote_systemd_value(value: str, *, variable_expansion: bool = True) -> str:
    """Encode *value* as a double-quoted systemd directive argument.

    systemd strips quotes after parsing, so a quoted value preserves embedded
    whitespace.  It also performs ``%`` specifier expansion everywhere and
    ``$`` environment expansion in ``Environment=`` (and command-line)
    assignments, so literal ``%`` and ``$`` must be doubled; backslashes and
    double quotes are escaped for the quoted form.  Passing this encoder the
    repository, plan, and ``PATH`` values keeps them byte-for-byte literal
    once systemd has parsed the directive.
    """
    text = value.replace("\\", "\\\\").replace('"', '\\"')
    text = text.replace("%", "%%")
    if variable_expansion:
        text = text.replace("$", "$$")
    return f'"{text}"'


def render_dropin(
    template_text: str, *, repo: Path, plan: str, path_value: str
) -> str:
    """Render the plan drop-in: header, substituted placeholders, PATH line."""
    body = template_text
    marker = "\n[Service]"
    index = body.find(marker)
    if index != -1:
        # Drop the template's instructional preamble; the generated header
        # replaces it in the managed file.
        body = body[index + 1 :]
    # WorkingDirectory is not subject to environment-variable expansion, but
    # specifier expansion still applies; Environment values expand both.
    body = body.replace(
        "${OPSX_AUTOPILOT_REPO}",
        _quote_systemd_value(str(repo), variable_expansion=False),
    )
    body = body.replace(
        "${OPSX_AUTOPILOT_PLAN}", _quote_systemd_value(plan)
    )

    path_line = f"Environment=PATH={_quote_systemd_value(path_value)}"
    lines: list[str] = []
    for line in body.splitlines():
        lines.append(line)
        if line.startswith("Environment=OPSX_PLAN="):
            lines.append(path_line)
    rendered = "\n".join(lines)
    if not rendered.endswith("\n"):
        rendered += "\n"
    return GENERATED_HEADER + rendered


def render_document(
    unit_path: Path, unit_text: str, dropin_path: Path, dropin_text: str
) -> str:
    """The ``--print`` payload: both rendered files, labeled by destination."""
    parts: list[str] = []
    for path, text in ((unit_path, unit_text), (dropin_path, dropin_text)):
        parts.append(f"# --- {path} ---\n")
        parts.append(text if text.endswith("\n") else text + "\n")
    return "".join(parts)


def systemctl_commands(unit_name: str, *, no_enable: bool = False) -> list[list[str]]:
    """The systemctl invocations for a successful install; never ``start``."""
    commands = [["systemctl", "--user", "daemon-reload"]]
    if not no_enable:
        commands.append(["systemctl", "--user", "enable", unit_name])
    return commands


def _default_runner(argv: list[str]):
    return subprocess.run(argv, text=True, capture_output=True, check=False)


def _normalize_unit_name(unit_name: str | None) -> str:
    """Return a safe single-component systemd unit basename.

    ``--unit-name`` is interpolated into filesystem paths and into the
    ``systemctl enable`` argv, so anything that is not a plain basename is
    rejected before any render, write, or ``systemctl`` call: absolute paths,
    path separators, traversal, whitespace/control characters, empty names, and
    leading-dash names (which ``systemctl`` would read as an option).
    """
    raw = DEFAULT_UNIT_NAME if unit_name is None else unit_name.strip()
    if raw.endswith(UNIT_NAME_SUFFIX):
        raw = raw[: -len(UNIT_NAME_SUFFIX)]
    if (
        not raw
        or raw in {".", ".."}
        or ".." in raw
        or "/" in raw
        or "\\" in raw
        or not UNIT_NAME_RE.fullmatch(raw)
    ):
        raise InstallError(
            f"invalid unit name {unit_name!r}: expected a single systemd unit "
            f"basename such as {DEFAULT_UNIT_NAME!r}"
        )
    return raw


def cmd_autopilot_install(
    args,
    *,
    runner=None,
    which_func=None,
    user_unit_dir: Path | None = None,
    template_root: Path | None = None,
) -> int:
    """``opsx-plan autopilot install`` handler.

    Optional keyword arguments exist for tests: *runner* replaces the
    systemctl subprocess wrapper, *which_func* replaces :func:`shutil.which`,
    *user_unit_dir* replaces ``~/.config/systemd/user``, and *template_root*
    pins the runtime root carrying the ``systemd/`` templates.
    """
    repo = Path(args.repo).resolve()
    print_only = bool(
        getattr(args, "print_only", False) or getattr(args, "print", False)
    )
    no_enable = bool(getattr(args, "no_enable", False))

    try:
        # Validate before resolving the plan or touching the filesystem so an
        # unsafe name can never reach a path or a systemctl argv.
        unit_name = _normalize_unit_name(getattr(args, "unit_name", None))
    except InstallError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    try:
        plan_src = planref.resolve_plan(repo, getattr(args, "plan", None))
        plan_path = planref._resolve_plan_path(repo, plan_src)
        cfg = planref.load_plan(plan_path, repo=repo)
    except base.PlanError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    try:
        root = resolve_template_root(template_root)
        unit_text = (root / UNIT_TEMPLATE_REL).read_text(encoding="utf-8")
        dropin_template = (root / DROPIN_TEMPLATE_REL).read_text(encoding="utf-8")
    except (InstallError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    try:
        path_value = derive_path(
            cfg.get("adapter", "opencode"), which_func=which_func or shutil.which
        )
        dropin_text = render_dropin(
            dropin_template,
            repo=repo,
            plan=str(plan_path),
            path_value=path_value,
        )
    except (InstallError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    unit_dir = Path(user_unit_dir) if user_unit_dir else _default_user_unit_dir()
    unit_path = unit_dir / f"{unit_name}.service"
    dropin_path = unit_dir / f"{unit_name}.service.d" / "plan.conf"

    if print_only:
        sys.stdout.write(render_document(unit_path, unit_text, dropin_path, dropin_text))
        return 0

    try:
        unit_path.parent.mkdir(parents=True, exist_ok=True)
        unit_path.write_text(unit_text, encoding="utf-8")
        dropin_path.parent.mkdir(parents=True, exist_ok=True)
        dropin_path.write_text(dropin_text, encoding="utf-8")
    except OSError as exc:
        print(f"error: failed to write {unit_path}: {exc}", file=sys.stderr)
        return 2

    run = runner or _default_runner
    try:
        for argv in systemctl_commands(unit_name, no_enable=no_enable):
            proc = run(argv)
            rc = getattr(proc, "returncode", 0)
            if rc != 0:
                stderr = (getattr(proc, "stderr", "") or "").strip()
                detail = f"{' '.join(argv)} failed (exit {rc})"
                if stderr:
                    detail = f"{detail}: {stderr}"
                raise InstallError(detail)
    except (InstallError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    state = "enabled" if not no_enable else "not enabled"
    print(f"installed {unit_path} and {dropin_path} ({state})")
    return 0
