"""``opsx-plan models`` subcommand group (show / env / init).

Moved verbatim from the ``orchestrator/opsx-plan.py`` entrypoint, together
with the private ``_resolve_models_adapter`` helper only this group uses
(design D2).
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import sys
from pathlib import Path

from lib.models.resolver import (
    USER_CONFIG_PATH,
    ModelConfigError,
    resolve as resolve_models,
    validate as validate_models,
)
from lib.models.types import ALL_ROLES, ROLE_ENV, ROLE_VARIANT_ENV, ROLES
from lib.orchestrator import base, planref


def _resolve_models_adapter(args: argparse.Namespace, repo: Path) -> str:
    """Resolve the target adapter for ``models show``/``models env``.

    Uses ``--adapter`` when given. Otherwise resolves the active plan the
    same way other operator commands do, so the two subcommands can run
    with no plan active as long as ``--adapter`` is supplied.
    """
    adapter = getattr(args, "adapter", None)
    if adapter:
        return adapter
    plan_src = planref.resolve_plan(repo, None)
    cfg = planref.load_plan(planref._resolve_plan_path(repo, plan_src), repo=repo)
    return cfg["adapter"]


def cmd_models_show(args: argparse.Namespace) -> int:
    """opsx-plan models show [--adapter <name>] — print resolved models."""
    repo = Path(args.repo).resolve()
    try:
        adapter = _resolve_models_adapter(args, repo)
    except base.PlanError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    try:
        resolved = resolve_models(adapter, repo=repo)
    except ModelConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    print(f"adapter: {adapter}")
    for role in ALL_ROLES:
        entry = resolved[role]
        value = entry.model if entry.model else "(unresolved)"
        print(f"  {role:<12} {value}  [{entry.source}]")
        if entry.variant:
            print(f"  {'':<12} variant: {entry.variant}  [{entry.variant_source}]")

    warnings = validate_models(adapter, resolved)
    if warnings:
        print("\nidentifier-syntax warnings:")
        for warning in warnings:
            print(f"  - {warning}")

    return 0


def cmd_models_env(args: argparse.Namespace) -> int:
    """opsx-plan models env [--adapter <name>] — print shell export statements."""
    repo = Path(args.repo).resolve()
    try:
        adapter = _resolve_models_adapter(args, repo)
    except base.PlanError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    try:
        resolved = resolve_models(adapter, repo=repo)
    except ModelConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    unresolved = [role for role in ROLES if not resolved[role].model]
    if unresolved:
        print(
            f"error: cannot emit environment for adapter '{adapter}': "
            f"unresolved role(s): {', '.join(unresolved)}",
            file=sys.stderr,
        )
        return 1

    for role in ROLES:
        print(f"export {ROLE_ENV[role]}={shlex.quote(resolved[role].model)}")
    # Emit the escalation export only when resolved.
    esc_entry = resolved.get("implementer_escalation")
    if esc_entry and esc_entry.model:
        print(f"export {ROLE_ENV['implementer_escalation']}={shlex.quote(esc_entry.model)}")
    # Emit reasoning-variant exports only when resolved; the installer keeps
    # the agent file's built-in default when no variant is configured.
    for role in ALL_ROLES:
        entry = resolved.get(role)
        if entry and entry.variant:
            print(f"export {ROLE_VARIANT_ENV[role]}={shlex.quote(entry.variant)}")
    return 0


def cmd_models_init(args: argparse.Namespace) -> int:
    """opsx-plan models init [--force] — seed the user-global config file."""
    path = USER_CONFIG_PATH
    if path.exists() and not getattr(args, "force", False):
        print(
            f"error: {path} already exists; use --force to overwrite",
            file=sys.stderr,
        )
        return 1

    lines = [
        "# Generated by `opsx-plan models init`.",
        "# See models.example.toml in the opsx-controller repo for the full",
        "# per-adapter precedence explanation.",
        "",
        "[defaults]",
    ]
    seeded = 0
    for role in ALL_ROLES:
        value = os.environ.get(ROLE_ENV[role], "").strip()
        if value:
            lines.append(f"{role} = {json.dumps(value)}")
            seeded += 1
    if seeded == 0:
        lines.append("# no OPSX_*_MODEL variables were set in the environment;")
        lines.append("# edit this file directly, e.g.:")
        lines.append('# controller = "github-copilot/gpt-5.4"')

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    if seeded:
        print(f"Created {path} ({seeded} role(s) seeded from the environment)")
    else:
        print(f"Created {path} (no environment values found; edit it directly)")
    return 0
