#!/usr/bin/env python3
"""Generate every distributed phase-agent file from canonical bodies.

The implementer, reviewer, and archiver instruction bodies are authored once
under ``core/phase-agents/``. Each distribution keeps a thin template under
``<distribution>/agent-templates/`` that carries only client-specific metadata
and steps and a single ``{{phase_body}}`` placeholder. This generator renders
the committed agent files from those shared inputs.

Every generated output starts with a header naming this generator and the
canonical source. Rendering is deterministic: LF line endings, no timestamps,
fixed iteration order. Run with ``--check`` to report drift without writing.

Usage:
    python3 scripts/generate-phase-agents.py
    python3 scripts/generate-phase-agents.py --check
"""

from __future__ import annotations

import argparse
import sys
from collections import OrderedDict
from pathlib import Path

PHASES = ("implementer", "reviewer", "archiver")

PLACEHOLDER = "{{phase_body}}"

# (output path, template path, header style) for every generated file. The
# Codex plugin copy shares the adapter template so it stays byte-identical.
_SPECS = (
    (
        "adapters/opencode/agents/opsx-{phase}.md",
        "adapters/opencode/agent-templates/opsx-{phase}.md.tmpl",
        "yaml",
    ),
    (
        "adapters/claude-code/agents/opsx-{phase}.md",
        "adapters/claude-code/agent-templates/opsx-{phase}.md.tmpl",
        "yaml",
    ),
    (
        "adapters/codex-cli/agents/opsx-{phase}.toml",
        "adapters/codex-cli/agent-templates/opsx-{phase}.toml.tmpl",
        "toml",
    ),
    (
        "adapters/dsh/agents/opsx-{phase}.md",
        "adapters/dsh/agent-templates/opsx-{phase}.md.tmpl",
        "html",
    ),
    (
        "adapters/codex-cli/plugin/agents/opsx-{phase}.toml",
        "adapters/codex-cli/agent-templates/opsx-{phase}.toml.tmpl",
        "toml",
    ),
    (
        "plugins/opsx-controller/agents/opsx-{phase}.md",
        "plugins/opsx-controller/agent-templates/opsx-{phase}.md.tmpl",
        "yaml",
    ),
)


class GenerateError(Exception):
    """A malformed canonical body or template stopped generation."""


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def _body(root: Path, phase: str) -> str:
    path = root / "core" / "phase-agents" / f"{phase}.md"
    if not path.is_file():
        raise GenerateError(f"missing canonical body: {path}")
    body = _read_text(path).strip("\n")
    if not body:
        raise GenerateError(f"empty canonical body: {path}")
    return body


def _render_one(root: Path, phase: str, template_rel: str, style: str) -> str:
    template_path = root / template_rel
    if not template_path.is_file():
        raise GenerateError(f"missing template: {template_path}")
    template = _read_text(template_path).strip("\n")
    count = template.count(PLACEHOLDER)
    if count != 1:
        raise GenerateError(
            f"{template_path} must contain exactly one {PLACEHOLDER} "
            f"placeholder, found {count}"
        )
    content = template.replace(PLACEHOLDER, _body(root, phase))
    content = content.rstrip("\n") + "\n"
    return _insert_header(content, style, phase)


def _insert_header(content: str, style: str, phase: str) -> str:
    note = (
        "Generated by scripts/generate-phase-agents.py from "
        f"core/phase-agents/{phase}.md; do not edit by hand."
    )
    if style == "yaml":
        # Keep YAML frontmatter as the first line; the marker is the first
        # comment inside it so the file's opening lines identify it.
        newline = content.index("\n")
        return f"{content[:newline + 1]}# {note}\n{content[newline + 1:]}"
    if style == "toml":
        return f"# {note}\n{content}"
    if style == "html":
        return f"<!-- {note} -->\n\n{content}"
    raise GenerateError(f"unknown header style: {style}")


def render_outputs(root: Path) -> "OrderedDict[str, str]":
    """Return ``{repo-relative output path: rendered text}`` for every file."""
    outputs: "OrderedDict[str, str]" = OrderedDict()
    for output_template, template_rel, style in _SPECS:
        for phase in PHASES:
            output_rel = output_template.format(phase=phase)
            template_path = template_rel.format(phase=phase)
            outputs[output_rel] = _render_one(root, phase, template_path, style)
    return outputs


def write_outputs(root: Path, output_root: Path) -> list[Path]:
    """Write every rendered output under *output_root*; return written paths."""
    written: list[Path] = []
    for relative, text in render_outputs(root).items():
        destination = output_root / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(text, encoding="utf-8", newline="\n")
        written.append(destination)
    return written


def check_outputs(root: Path) -> list[str]:
    """Return the repo-relative paths whose committed copy differs."""
    drifted: list[str] = []
    for relative, expected in render_outputs(root).items():
        path = root / relative
        if not path.is_file():
            drifted.append(relative)
            continue
        if path.read_bytes() != expected.encode("utf-8"):
            drifted.append(relative)
    return drifted


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report files that differ from the committed copy and exit non-zero",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root containing canonical bodies and templates",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=None,
        help="write generated files under this root (default: --root)",
    )
    args = parser.parse_args(argv)

    root = args.root.resolve()
    try:
        if args.check:
            drifted = check_outputs(root)
            if drifted:
                for relative in drifted:
                    print(f"drift: {relative}")
                print(
                    f"{len(drifted)} generated file(s) differ; "
                    "run scripts/generate-phase-agents.py",
                    file=sys.stderr,
                )
                return 1
            print(f"ok: {len(render_outputs(root))} generated file(s) up to date")
            return 0

        output_root = (args.output_root or root).resolve()
        written = write_outputs(root, output_root)
        for path in written:
            print(f"wrote {path}")
        return 0
    except GenerateError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
